menu:
- {name: 'Research', url: '/research'}
- {name: 'Publications', url: '/publications'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

research:
- {name: 'Molecular Materials AI', image: 'assets/img/plans1.png'}
- {name: 'Accelerated Atomistic Compute', image: 'assets/img/plans2.png'}
- {name: 'Nanoscale Charge and Temperature Mapping', image: 'assets/img/plans3.png'}
#- {name: 'Energy conversion and transport', image: 'assets/img/plans.jpg'}
#- {name: 'Thermal transport in novel inorganic materials', image: 'assets/img/porous.jpg'}

social:
- {icon: 'github', link: 'https://github.com/qichensong'}
- {icon: 'twitter', link: 'https://twitter.com/qichensong'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=RVTEIugAAAAJ&hl=en'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/qichensong'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0002-1090-4068'}

contacts:
- {name: 'Dr. Qichen Song (宋琪琛)', title: 'Harvard Quantum Initiative Postdoctoral fellow', department: 'Department of Chemistry & Chemical Biology', institution: 'Harvard University', institution_address: '12 Oxford Street, Cambridge, MA', email: 'qichensong@g.harvard.edu', office: 'Naito 312', image: 'assets/img/contact.jpg'}
